
version: '3.8'

services:
  benchmark-service:
    build: .
    
    ports:
      - "8002:8002"
    
    volumes:
      - ./data:/app/data
    
    environment:
      - PYTHONPATH=/app
      
    restart: unless-stopped